# Generated by Django 4.1.4 on 2022-12-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='conf',
        ),
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(default='s', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='secret_key',
            field=models.CharField(default='a', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
